### ISSUE TITLE
01/02 - Tasks - feature/DDDArchitecture

### ISSUE THREAD

**Issue by antoniodecastroalves** [antoniodecastroalves/iniciando-back-end-do-app#3]
### DDD Architecture

- [x] Introduction
- [x] DDD and TDD concepts
- [x] Separating into modules
- [x] Infra Layer
- [x] Configuring Imports
- [x] Liskov Substitution Principle
- [x] Rewriting Repositories
- [x] Dependency Inversion Principle
- [x] Refactoring users module
- [x] Dependency injection
- [x] Using controllers

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
 Introduction, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
DDD and TDD concepts, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Separating into modules, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
 Infra Layer, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Configuring Imports, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Liskov Substitution Principle, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Rewriting Repositories, Finished!

**Comment by antoniodecastroalves** [comment]
Task accomplished!
Dependency Inversion Principle, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Refactoring users module, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Dependency injection, Finished!

**Comment by antoniodecastroalves** [comment]
Task accomplished!
Using controllers, Finished!
