### ISSUE TITLE
02/02 - Tasks - feature/testsAndTDD

### ISSUE THREAD

**Issue by antoniodecastroalves** [antoniodecastroalves/iniciando-back-end-do-app#5]
### Tests and TDD

- [x] Tests and TDD
- [x] Configuring Jest
- [x] Thinking about the tests
- [x] Creating the first test
- [x] Coverage report
- [x] Scheduling tests
- [x] Testing user creation
- [x] Testing authentication
- [x] Authentication tests
- [x] Storage Provider
- [x] Avatar Update

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Tests and TDD, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Configuring Jest, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Thinking about the tests, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Creating the first test, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Coverage report, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Scheduling tests, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
 Testing user creation, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!

Testing authentication, Finished!

**Comment by antoniodecastroalves** [comment]
Task accomplished!
Authentication tests, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Storage Provider, Finished!

**Comment by antoniodecastroalves** [comment]
### Task accomplished!
Avatar Update, Finished!
